package ua.coffeetamine.common.identity;

import java.util.UUID;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.Table;
import jakarta.persistence.UniqueConstraint;

import ua.coffeetamine.common.domain.model.BaseAuditableEntity;

import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;
import lombok.experimental.SuperBuilder;

/**
 * Maps an OIDC {@code (issuer, subject)} tuple to a stable internal {@code app_user_id} UUID. The
 * {@code id} (surrogate PK) is generated by Hibernate; {@code app_user_id} is generated by the
 * service at provisioning time and is the value feature tables key on.
 *
 * <p>{@code (issuer, subject)} is the natural key — immutable once written. {@code email} is
 * best-effort metadata and may be refreshed on subsequent logins.
 */
@Entity
@Table(
    name = "external_identities",
    uniqueConstraints =
        @UniqueConstraint(
            name = "uk_external_identities_issuer_subject",
            columnNames = {"issuer", "subject"}))
@Getter
@Setter
@NoArgsConstructor
@SuperBuilder
public class ExternalIdentity extends BaseAuditableEntity {

  @Column(name = "app_user_id", nullable = false, updatable = false)
  private UUID appUserId;

  @Column(name = "issuer", nullable = false, length = 512, updatable = false)
  private String issuer;

  @Column(name = "subject", nullable = false, updatable = false)
  private String subject;

  @Column(name = "email", length = 320)
  private String email;
}
